print("error and exception handing")